leftnav:
- identifier: f4aa30b6-d2a2-1324-bc03-6cdb9cbd2d1c
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: e9f03870-c27b-344a-0a1c-225d8f0d42ab
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 3282cf66-e7cb-cdd9-f161-ddd7f48bfde2
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 583ced2c-57eb-da08-5094-6ccd89e72591
  name: Session Summaries
  url: /pages/session-summaries
  weight: 40
- identifier: 189de72e-9204-f59a-055d-08434b009be1
  name: Projects
  url: /pages/projects
  weight: 50
